[package]
name = "noirvault"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[lib]
crate-type = ["rlib", "staticlib"]

[[bin]]
name = "noirvault"
path = "src/main.rs"
required-features = ["desktop"]

[features]
default = ["desktop"]
desktop = ["dep:arboard", "dep:enigo", "dep:machine-uid", "dep:rfd", "dep:slint", "dep:totp-rs"]

[dependencies]
slint = { version = "1.7.0", optional = true }
argon2 = "0.5.3"
chacha20poly1305 = { version = "0.10.1", features = ["alloc", "stream"] }
zeroize = { version = "1.8.1", features = ["zeroize_derive", "alloc"] }
rand = "0.8.5"
rfd = { version = "0.14.1", optional = true }
sha2 = "0.11.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
base64 = "0.22"
uuid = { version = "1.0", features = ["v4"] }
arboard = { version = "3.4.0", optional = true }
totp-rs = { version = "5.5", optional = true }
enigo = { version = "0.1", optional = true }
machine-uid = { version = "0.3", optional = true }
hex = "0.4"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.59.0", features = ["Win32_System_Memory", "Win32_System_Threading", "Win32_System_LibraryLoader", "Win32_Foundation", "Win32_System_SystemInformation", "Win32_System_Diagnostics_Debug"] }

[target.'cfg(any(target_os = "linux", target_os = "ios", target_os = "macos"))'.dependencies]
libc = "0.2.155"

[build-dependencies]
slint-build = "1.7.0"
winres = "0.1"
